"""empty message

Revision ID: 17106e12f127
Revises: 4df6cb5cf638
Create Date: 2015-08-15 15:22:25.998000

"""

# revision identifiers, used by Alembic.
revision = '17106e12f127'
down_revision = '4df6cb5cf638'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
