"""empty message

Revision ID: 3c4c318a7d0b
Revises: 6ce20f9e3a9
Create Date: 2015-10-07 05:50:32.902000

"""

# revision identifiers, used by Alembic.
revision = '3c4c318a7d0b'
down_revision = '6ce20f9e3a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('imageurl', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'imageurl')
    ### end Alembic commands ###
