"""empty message

Revision ID: 3d5302d6bdd7
Revises: None
Create Date: 2015-08-12 02:53:20.980000

"""

# revision identifiers, used by Alembic.
revision = '3d5302d6bdd7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SMS')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SMS',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
