"""empty message

Revision ID: 49f929780ca4
Revises: 3d5302d6bdd7
Create Date: 2015-08-12 04:03:06.163000

"""

# revision identifiers, used by Alembic.
revision = '49f929780ca4'
down_revision = '3d5302d6bdd7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('birth_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmer', 'birth_date')
    ### end Alembic commands ###
