"""empty message

Revision ID: 4df6cb5cf638
Revises: 5ccbebd8335
Create Date: 2015-08-15 15:15:54.889000

"""

# revision identifiers, used by Alembic.
revision = '4df6cb5cf638'
down_revision = '5ccbebd8335'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    ### end Alembic commands ###
