"""empty message

Revision ID: 5ccbebd8335
Revises: 49f929780ca4
Create Date: 2015-08-14 02:13:11.170000

"""

# revision identifiers, used by Alembic.
revision = '5ccbebd8335'
down_revision = '49f929780ca4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('group', sa.String(length=80), nullable=True),
    sa.Column('info', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
