"""empty message

Revision ID: 6ce20f9e3a9
Revises: 9f6f77334e9
Create Date: 2015-10-07 05:33:57.493000

"""

# revision identifiers, used by Alembic.
revision = '6ce20f9e3a9'
down_revision = '9f6f77334e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('base_price', sa.Numeric(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'base_price')
    ### end Alembic commands ###
